/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Jni */

#ifndef _Included_example_Jni
#define _Included_example_Jni
#ifdef __cplusplus
extern "C" {
#endif

	/*
	* Class:     example_Jni
	* Method:    DisplayHello
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_example_Jni_DisplayHello
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
