/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Jni */

#ifndef _Included_example_Jni
#define _Included_example_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_Jni
 * Method:    displayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_Jni_displayHello
  (JNIEnv *, jclass);

/*
 * Class:     example_Jni
 * Method:    getAnsiString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_Jni_getAnsiString
  (JNIEnv *, jclass);

/*
 * Class:     example_Jni
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_example_Jni_printString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
