/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_Bean_Wifi */

#ifndef _Included_com_ifancc_wifimgr_Bean_Wifi
#define _Included_com_ifancc_wifimgr_Bean_Wifi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifancc_wifimgr_Bean_Wifi
 * Method:    getWifiNames
 * Signature: ()[Lcom/ifancc/wifimgr/Bean/Wifi;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ifancc_wifimgr_Bean_Wifi_getWifiNames
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
