/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_Bean_WlanInterfaceState */

#ifndef _Included_com_ifancc_wifimgr_Bean_WlanInterfaceState
#define _Included_com_ifancc_wifimgr_Bean_WlanInterfaceState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifancc_wifimgr_Bean_WlanInterfaceState
 * Method:    getWlanInterfaceState
 * Signature: (I)Lcom/ifancc/wifimgr/Bean/WlanInterfaceState;
 */
JNIEXPORT jobject JNICALL Java_com_ifancc_wifimgr_Bean_WlanInterfaceState_getWlanInterfaceState
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
