/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_WlanInterfaceInfoListTest */

#ifndef _Included_com_ifancc_wifimgr_WlanInterfaceInfoListTest
#define _Included_com_ifancc_wifimgr_WlanInterfaceInfoListTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifancc_wifimgr_WlanInterfaceInfoListTest
 * Method:    getWlanInterfaceInfoList
 * Signature: ()Lcom/ifancc/wifimgr/Bean/WlanInterfaceInfoList;
 */
JNIEXPORT jobject JNICALL Java_com_ifancc_wifimgr_WlanInterfaceInfoListTest_getWlanInterfaceInfoList
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
