/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_Manager */

#ifndef _Included_com_ifancc_wifimgr_Manager
#define _Included_com_ifancc_wifimgr_Manager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifancc_wifimgr_Manager
 * Method:    getWifiList
 * Signature: ()[Lcom/ifancc/wifimgr/Bean/Wifi;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ifancc_wifimgr_Manager_getWifiList
  (JNIEnv *, jobject);

/*
 * Class:     com_ifancc_wifimgr_Manager
 * Method:    WlanEnumInterfaces
 * Signature: ()Lcom/ifancc/wifimgr/Bean/WlanInterfaceInfoList;
 */
JNIEXPORT jobject JNICALL Java_com_ifancc_wifimgr_Manager_WlanEnumInterfaces
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
