/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_Bean_WlanInterfaceInfoList */

#ifndef _Included_com_ifancc_wifimgr_Bean_WlanInterfaceInfoList
#define _Included_com_ifancc_wifimgr_Bean_WlanInterfaceInfoList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
