/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_Bean_WlanInterfaceInfo */

#ifndef _Included_com_ifancc_wifimgr_Bean_WlanInterfaceInfo
#define _Included_com_ifancc_wifimgr_Bean_WlanInterfaceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifancc_wifimgr_Bean_WlanInterfaceInfo
 * Method:    getWlanInterfaceInfo
 * Signature: ()Lcom/ifancc/wifimgr/Bean/WlanInterfaceInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ifancc_wifimgr_Bean_WlanInterfaceInfo_getWlanInterfaceInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
