/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifancc_wifimgr_WlanInterfaceInfoTest */

#ifndef _Included_com_ifancc_wifimgr_WlanInterfaceInfoTest
#define _Included_com_ifancc_wifimgr_WlanInterfaceInfoTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifancc_wifimgr_WlanInterfaceInfoTest
 * Method:    getWlanInterfaceInfo
 * Signature: ()Lcom/ifancc/wifimgr/Bean/WlanInterfaceInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ifancc_wifimgr_WlanInterfaceInfoTest_getWlanInterfaceInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
